version: '1'

services:
  rvc:
    build:
      context: .
      dockerfile: Dockerfile.amd
    container_name: rvc
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: amd
              count: 1
              capabilities: [gpu]